name:    yesod-app
version: "0.0.0"

default-extensions:
  - DeriveAnyClass
  - TransformListComp
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - StandaloneDeriving
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - LambdaCase
  - UndecidableInstances
  - TypeApplications


dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base

- yesod
- yesod-core
- yesod-static
- yesod-form
- yesod-auth
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- bytestring
- text
- blaze-html
- template-haskell
- shakespeare
- hjsmin
- monad-control
- wai-extra
- yaml
- http-client-tls
- http-conduit
- directory
- warp
#- data-default
#- aeson
#- conduit
#- monad-logger
#- fast-logger
#- wai-logger
#- mime-mail
#- file-embed
#- safe
#- unordered-containers
#- containers
#- vector
#- time
#- case-insensitive
#- wai
#- foreign-store
#- persistent
#- persistent-template
#- persistent-postgresql
#- esqueleto

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-incomplete-patterns
      - -fwarn-tabs
      - -O2
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wredundant-constraints
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-incomplete-patterns
      - -fwarn-tabs
      - -O2
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wredundant-constraints

# Runnable executable for our application
executables:
  yesod-app:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4-AL32m-n4m-A32m-qb0-I0
    dependencies:
    - yesod-app
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  yesod-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - yesod-app
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
